name: Build and Release Windows EXE

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download SFML 3.0.0
      run: |
        curl -L -o sfml.zip https://www.sfml-dev.org/files/SFML-3.0.0-windows-vc17-64-bit.zip
        7z x sfml.zip -osfml

    - name: Setup MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DSFML_DIR="${{ github.workspace }}/sfml/SFML-3.0.0/lib/cmake/SFML"

    - name: Build with CMake
      run: cmake --build build --config Release

    - name: Prepare zip content
      run: |
        mkdir dist
        copy build\Release\Farmer_Life__Outside_the_town.exe dist\
        copy sfml\SFML-3.0.0\bin\*.dll dist\
        if exist data xcopy data dist\data\ /E /I /Y

    - name: Create zip archive
      run: |
        powershell Compress-Archive -Path dist\* -DestinationPath Farmer_Life_Windows.zip

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: Farmer_Life_Windows.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
